[package]
name = "chromium"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["rlib"]

[profile.release]
lto = true
codegen-units = 1

[dependencies]
chromium_jni_utils = { path = "../chromium_jni_utils/" }
chromium_jni_macro = { path = "../chromium_jni_macro/" }
jni = "0.19.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "libloaderapi"] }

[features]
gen = ["bindgen"]

[build-dependencies]
bindgen = { version = "0.59.0", optional = true }
