[package]
name = "chromium_jni_macro"
edition = "2021"
version = "101.0.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.92", features = ["parsing", "full", "proc-macro"] }
quote = "1.0"
proc-macro2 = "1.0.32"